services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Argentina/Buenos_Aires"
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - warez:/data
    networks:
      - srv
    ports:
      - 8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
